inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineOperationIndentation:
  Enabled: true

# Cop supports --auto-correct.
Layout/EmptyLines:
  Enabled: true

Metrics/ModuleLength:
  Exclude:
  - test/**/*
